version: 2.1
orbs:
  php: circleci/php@1.1.0

jobs:
  test-php:
    docker:
      - image: cimg/php:8.2.7
    steps:
      - checkout
      - php/install-composer:
          install-version: 1.10.16
      - run:
          name: Set permissions for PHPUnit
          command: chmod +x ./vendor/bin/phpunit
      - run:
          name: Run PHPUnit Tests
          command: ./vendor/bin/phpunit --log-junit test-results.xml HelloTest.php
      - store_test_results:
          path: test-results.xml
      - store_artifacts:
          path: test-results.xml
          destination: test-results


workflows:
  build-and-test:
    jobs:
      - test-php
      
